server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      inventory-status: inventoryStatusEvent

  application:
    name: order-service

  datasource:
    url: jdbc:h2:file:./data/order-db;AUTO_RECONNECT=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  h2:
    console:
      enabled: true
      path: /h2-console  # open in browser http://localhost:8082/h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  main:
    banner-mode: "off"

logging:
  level:
    org.springframework: "ERROR"
    org.hibernate: "ERROR"
    root: "WARN"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
